reservation/bookili/urls.py
from django.urls import path
from . import views
app_name ='bookili'
urlpatterns = [
    path('',views.Accueil,name='accueil'),
    path('inscription/',views.inscription,name='inscription'),
    path('InscriptionClient/',views.InscriptionClient,name='InscriptionClient'),
    path('connexion/',views.connexion,name='connexion'),
    path('ConnexionClient/',views.ConnexionClient,name='ConnexionClient'),
    path('deconnexion/',views.deconnexion,name='deconnexion'),
    path('features/',views.Accueil,name='features'),
    path('tarifs/',views.Accueil,name='tarifs'),
    path('inscription/structure/',views.CreateStructure,name='structure'),
    path('inscription/structure/service/',views.Service,name='service'),
    path('inscription/structure/service/staff/',views.CreateStaff,name='staff'),
    path('connexion/profile/DetailStructure/<int:id>',views.AfficherStructure,name ='AfficherStructure'),
    path('connexion/profile/DetailStaff/<int:id>',views.AfficherStaff,name ='AfficherStaff'),
    path('profile/',views.Profile,name='Profile'),
    path('proprietaire/',views.All,name='All'),
]

reservation/reservation/urls.py
#from django.conf import settings
from django.contrib import admin
from django.urls import path, include,re_path
#from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookili/', include('bookili.urls')),
    path('accounts/', include('allauth.urls')),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/bookili/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Proprietaire, Structure as StructureModel, Service, Staff, Servir, Client as ClientModel, CatergorieStructure
from django.contrib.auth.forms import UserCreationForm

#Inscripion compte user (Propriétaire)
class Inscription(UserCreationForm):
    # mot_de_passe = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(label='Utilisateur')
    password1 = forms.CharField(help_text=False,label='password',widget=forms.PasswordInput)
    password2 = forms.CharField(help_text=False,label='confirmation password',widget=forms.PasswordInput)

    class Meta:
        model = User
        # fields = '__all__'
        fields =('username','email','password1','password2',)


class Structure(forms.ModelForm):
    catergorie_structure_idcatergorie_structure = forms.ModelChoiceField(queryset=CatergorieStructure.objects.all(),label='catégorie')
    class Meta:
        model = StructureModel
        # fields = '__all__'
        fields = ('nom_struct','adresse_struct','catergorie_structure_idcatergorie_structure','code_postal',)

class ServiceForm(forms.ModelForm):
    # structure_idstructure = forms.CharField(label='structure')
    debut_service = forms.TimeField(help_text='09:00')
    fin_service = forms.TimeField(help_text='11:00')
    structure_idstructure =forms.ModelChoiceField(queryset=StructureModel.objects.all(),label='type structure')

    class Meta:
        model = Service
        fields = ('nom_service','debut_service','fin_service','structure_idstructure',)
        # exclude =('structure_idstruc
class StaffForm(forms.ModelForm):
    structure_idstructure =forms.ModelChoiceField(queryset=StructureModel.objects.all(),label='type structure')
    
    class Meta:
        model = Staff
        # fields ='__all__'
        fields = ('nom_staff','prenom_staff','structure_idstructure',)

#
# class ServirForm(forms.ModelForm):
#     class Meta:
#         model = Servir
#         fields = '__all__'


#Inscripion compte Client :
class InscriptionClientForm(forms.ModelForm):
    mot_de_passe_client = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = ClientModel
        fields =('nom_client','email','mot_de_passe_client',)


class ConnexionClientForm(forms.ModelForm):
    mot_de_passe_client = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = ClientModel
        fields =('email','mot_de_passe_client',)

reservation/bookili/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Proprietaire, Structure as StructureModel, Service as ServiceModel, Staff as StaffModel, Servir, Client as ClientModel
from .forms import Inscription, Structure,ServiceForm, StaffForm, InscriptionClientForm, ConnexionClientForm
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist # pour gérer les exceptions

# Create your views here.
def Accueil(request):
    return render(request,'pages/accueil.html')

@login_required
def Service(request):
    form = ServiceForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit= False)
        instance.userpropr_id = request.user
        instance.save()
        # return redirect('/bookili/connexion/profile')
        return redirect('staff/')
    return render(request,'pages/service.html',{'form':form})

@login_required
def CreateStructure(request):
    form = Structure(request.POST or None)
    if form.is_valid():
        instance = form.save(commit= False)
        instance.userpropr = request.user
        instance.save()
        return redirect('service/',locals())
        form = Structure()
    return render (request,'pages/structure.html',{'form':form})

# @login_required
def CreateStaff(request):
    form = StaffForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit= False)
        instance.userpropr_id = request.user
        instance.save()
        return redirect('/bookili/profile/',locals())
        form = StaffForm()
    return render (request,'pages/staff.html',{'form':form})

# @login_required
# def AfficherService (request,id):
#     structure = StructureModel.objects.get(userpropr_id=id)
#     # for s in (StructureModel.objects.raw('SELECT * FROM STRUCTURE,auth_user WHERE userpropr_id = auth_user.id')):
#     #     s.username = request.user
#     #     req = s.username
#     # print(s[0].adresse_struct)
#     return render(request,'pages/afficherstructure.html',{'structure':structure})

@login_required
def AfficherStructure (request,id):
    try:
         structure = StructureModel.objects.filter(userpropr_id=id).all()
         service = ServiceModel.objects.filter(userpropr_id=id ).all()
    except ObjectDoesNotExist:
        return redirect ('/bookili/inscription/structure/service/')
        messages.error(request,'crée votre service')

    # for s in (StructureModel.objects.raw('SELECT * FROM STRUCTURE,auth_user WHERE userpropr_id = auth_user.id')):
    #     s.username = request.user
    #     req = s.username
    # print(s[0].adresse_struct)
    return render(request,'pages/afficherstructure.html',{'structure':structure,'service':service})


def AfficherStaff(request,id):
    try:
        staff = StaffModel.objects.filter(userpropr_id=id).all()
        print(staff)
    except ObjectDoesNotExist:
        messages.error(request,'ajout des staff')
        return redirect ('/bookili/inscription/structure/service/staff/')

    # for s in (StructureModel.objects.raw('SELECT * FROM STRUCTURE,auth_user WHERE userpropr_id = auth_user.id')):
    #     s.username = request.user
    #     req = s.username
    # print(s[0].adresse_struct)
    return render(request,'pages/afficherstaff.html',{'staff':staff})

#inscription compte Proprietaire de structure
def inscription(request):
    if request.method =="POST":
        form = Inscription(request.POST or None)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,"bienvenue:")
            login(request, user)
            # form = Inscripion()
            return redirect('structure/',locals())
    else :
        form = Inscription()
    return render(request,'pages/inscription.html',{'form':form})

def connexion(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username ,password = password)
            if user is not None:
                login(request,user)
                messages.success(request,'vous etes bien connecté !')
                # return redirect('/bookili',locals())
                return redirect('/bookili/profile/',locals())

            else :
                messages.error(request,'compte invalid !')
        else :
            messages.error(request,'compte invalid !')
    else :
        form = AuthenticationForm()
    return render(request,'pages/connexion.html',{'form':form})


def deconnexion(request):
      logout(request)
      del request.session
      return redirect('/bookili')


def Profile(request):
    profil = User.objects.get(username=request.user)
    return render(request,'pages/profile.html',{'profil':profil})


#inscription compte Client de structure
def InscriptionClient(request):
        form = InscriptionClientForm(data=request.POST or None)
        if form.is_valid():
            instance = ClientModel()
            instance.nom_client = form.cleaned_data['nom_client']
            instance.email = form.cleaned_data['email']
            instance.mot_de_passe_client = form.cleaned_data['mot_de_passe_client']
            instance.save()
            return redirect('/bookili/proprietaire/',locals())
        else :
            form = InscriptionClientForm()
        return render(request,'pages/InscriptionClient.html',{'form':form})

def ConnexionClient(request):
        form = ConnexionClientForm(request.POST or None)
        if form.is_valid():
            email1 = form.cleaned_data.get('email')
            mot_de_passe_client = form.cleaned_data.get('mot_de_passe_client')
            if (ClientModel.objects.filter(email=email1).exists()):
                if (ClientModel.objects.filter(mot_de_passe_client=mot_de_passe_client).exists()):
                    print('succes connexion')
                    return redirect('/bookili/proprietaire',locals())
                else:
                    print('error mot de passe !')
            else:
                print('echec connexion')
        return render(request,'pages/ConnexionClient.html',{'form':form})


def DeconnexionClient(request):
      logout(request)
      return redirect('/bookili')


def All(request):
    all = StaffModel.objects.all()
    # structure = StructureModel.objects.all()
    return render (request,'pages/recherchestaff.html',{'all':all})

reservation/bookili/templates/pages/ConnexionClient.html
{% extends "pages/base.html" %}
{% block content %}
  <div class="ui raised very padded text container segment">
    <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <h2 style="text-align:center;margin-bottom:1.5em;">Client</h2>
      <div class="ui field">Email
        {{form.email}}
      </div>
      <div class="ui divided "></div>
      <div class="ui field">Mot de passe
        {{form.mot_de_passe_client}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
      <a href="{% url 'bookili:InscriptionClient' %}">inscrivez vous</a></p>
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/InscriptionClient.html
{% extends "pages/base.html" %}

{% block content %}
  <div class="ui raised very padded text container segment">
    <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
    <p>vous avez déja un compte? <a href="{% url 'bookili:ConnexionClient' %}">connecter vous</a></p>
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/_content.html
{% load static %}
<!--début de corps du site -->
<div class="wrapper">
  <div class="content">
    <h1>systeme de réservation en ligne</h1>
    <div class="content-image">
      <img src="{% static "images/intro.jpg" %}" alt="">
    </div>
    <h2> <span>Plus de rendez-vous, moins de planifications </span> </br> </br>
      Le calendrier des planifications et le téléphone ne répondent plus aux besoins de vos clients.</br>
      Passez à un système de réservation puissant et simple.</h2>
    <div class="content-compte">
      <h1>créer votre compte</h1>
      <div class="content-compte-owner">
          <a href="{% url 'bookili:connexion' %}">Propriétaire</a>
      </div>
      <div class="content-compte-client">
          <a href="{% url 'bookili:InscriptionClient' %}">Client</a>
      </div>
      <div class="content-image-owner">
        <img src="{% static "images/owner.jpg"%}" alt="">
      </div>
      <div class="content-image-client">
        <img src="{% static "images/client.png"%}" alt="">
      </div>
    </div>
    <div class="content-fonction">
      <h1>Fonctionnalités</h1>
      <div class="content-fonction-items" clearfix>
        <div class="content-fonction-item">
          <i class="far fa-calendar-alt"></i>
          <h4> calendrier</h4>
          <p class="description">planification des rendez-vous</p>
        </div>
        <div class="content-fonction-item">
          <i class="fas fa-book"></i>
          <h4>Reservation en ligne</h4>
          <p class="description">Bookily accepte les réservations 24h/7</p>
        </div>
        <div class="content-fonction-item">
          <i class="fas fa-users"></i>
          <h4>Gestion des clients</h4>
          <p class="description">bookily offre un aperçu clair des clients</p>
        </div>
    </div>
    </div>
  </div>
  <div class="structure-items">
    <h1>Type de structures qui utilisent Bookily</h1>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/medical.jpg"%}" alt="">
      </div><p>Médical</p></div>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/soins.jpg"%}"alt="">
      </div><p>Beauté & soins</p></div>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/sport.jpg"%}"alt="">
      </div><p>Sport & loisirs</p></div>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/culture.jpg"%}"alt="">
      </div><p>Culture</p></div>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/cours.jpg"%}"alt="">
      </div><p>Cours & Education</p></div>
    <div class="struct-item">
      <div class="struct-item-image">
        <img src="{% static "images/autre.jpg"%}"alt="">
      </div><p>Autres</p></div>
  </div>
</div>
<!--fin du corps du site -->

reservation/bookili/templates/pages/_footer.html
<!-- début de la partie footer -->
<div class="footer">
  <div class="footer-border">
  </div>
  <div class="footer-nav">
    <ul>
      <p>Produit</p>
      <li>Fonctionnalités</li>
      <li>Guide</li>
      <li>Tarifs</li>
    </ul>
    <ul>
      <p>A propos de nous</p>
      <li>adresse</li>
      <li>blog</li>
      <li>Service client</li>
    </ul>
    <div class="langue">
        <i class="fas fa-globe-africa"></i>
        <ul>
          <li class="active">Langue</li>
          <li>Fr</li>
          <li>Ar</li>
          <li>En</li>
        </ul>
      </div>
  </div>
</div>
<!-- fin de la partie footer-->

reservation/bookili/templates/pages/_header.html
<!-- début de l'entete du site  -->
<div class="header">
  <div class="ui stackable menu">
    <div class="item">
      <a href="{% url 'bookili:accueil' %}">Accueil</a>
    </div>
      <a href="{% url 'bookili:features' %}"class="item">Fonctionnalités</a>
      <a href="{% url 'bookili:tarifs' %}"class="item">Tarifs</a>
      {% if user.is_authenticated %}
      <a href="{% url 'bookili:Profile' %}" class="item" id="username">{{user.username}}</a>
      <a href="{% url 'bookili:deconnexion' %}"class="item" id="logout">Deconnexion</a>
      {% else %}
      <a href="{% url 'bookili:inscription' %}"class="item">S'inscrire</a>
      <div class="type-compte">
        <a href="{% url 'bookili:accueil' %}"class="item" id="login">Se connecter</a>
          <ul class="ui raised very padded text container segment">
            <li class="type"><a href="{% url 'bookili:connexion' %}">Proprietaire</a></li>
            <li class="type"><a href="{% url 'bookili:ConnexionClient' %}">Client</a></li>
          </ul>
      </div>
      {% endif %}
    <div class="ui category search item">
      <div class="ui transparent icon input">
        <input class="prompt" type="text" placeholder="Recherche...">
        <i class="search link icon"></i>
      </div>
   </div>
  </div>
</div>

reservation/bookili/templates/pages/accueil.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css'%}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

</head>
<body>

</body>
</html>
<body>
  {% include 'pages/_header.html' %}
  {% include 'pages/_content.html' %}
  {% include 'pages/_footer.html' %}
</body>
<script type="text/javascript" src="{% static 'javascript/' %}">
</script>
</html>

reservation/bookili/templates/pages/afficherstructure.html
{% extends "pages/base.html" %}
{% block content %}
<div class="ui raised very padded text container segment">
    {% csrf_token %}
      <p>Ma structure</p>
    {% for struct in structure %}
    <div class="ui field">
      {{struct.nom_struct}}
    </div>
    <div class="ui divider"></div>
    <div class="ui field">
      {{struct.adresse_struct}}
    </div>
    <div class="ui divider"></div>
    <div class="ui field">
      {{struct.code_postal}}
    </div>
    {% empty %}
    <a href="{% url 'bookili:structure' %}">créez votre structure</a>
    {%endfor%}
    <div class="ui divider"></div>
      <p>Mon staff</p>
    <table class="ui definition table">
  <tbody>
    {% for serv in service %}
    <tr>
      <td class="two wide column">id service</td>
      <td>{{serv.idservice}}</td>
    </tr>
    <tr>
      <td>nom de service</td>
      <td>{{serv.nom_service}}</td>
    </tr>
    <tr>
      <td>duree de service</td>
      <td>{{serv.debut_service}}</td>
    </tr>
    <tr>
      <td>fin service</td>
      <td>{{serv.fin_service}}</td>
    </tr>
    {%endfor%}
  </tbody>
</table>
</div>
{% endblock %}

reservation/bookili/templates/pages/connexion.html
{% extends "pages/base.html" %}
{% load socialaccount %}
{% block content %}
  <div class="ui raised very padded text container segment">
    <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
      <a href="{% url 'bookili:inscription' %}">inscrivez vous</a></p>
      <a href="{% provider_login_url 'google' %}">Log In with Gmail</a>
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/inscription.html
{% extends "pages/base.html" %}

{% block content %}
  <div class="ui raised very padded text container segment">
    <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
    <p>vous avez déja un compte? <a href="{% url 'bookili:login' %}">connecter vous</a></p>
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/profile.html
{% extends "pages/base.html" %}
{% block content %}
<div class="ui raised very padded text container segment">
    {% csrf_token %}
    <p>Informations personnelles</p>
    <div class="ui divider"></div>
    <div class="ui field">
      {{profil.username}}
    </div>
    <div class="ui divider"></div>
    <div class="ui field">
      {{profil.email}}
    </div>
    <div class="ui divider"></div>
    <a href="{% url 'bookili:AfficherStructure' profil.id %}"class="item" id="structure">Ma Structure</a>
    <div class="ui divider"></div>
    <a href="{% url 'bookili:AfficherStaff' profil.id %}"class="item" id="staff">Mon staff</a>
</div>
{% endblock %}

reservation/bookili/templates/pages/recherchestaff.html
{% extends "pages/base.html" %}
{% block content %}
<div class="allusers">
  <div class="ui items">
    {% for a in all %}
    <div class="item">
      <div class="middle aligned content">
        <div class="header">
          {{a.idstaff}}#  {{a.nom_staff}} {{a.prenom_staff}}
        </div>
        <div class="description">
          <p>type de la structure proposée est :{{a.structure_idstructure}} et appartienne a :{{a.userpropr_id}}</p>
        </div>
        <div class="extra">
          <div class="ui right floated button">
            choisir
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

reservation/bookili/templates/pages/service.html
{% extends "pages/base.html" %}
{% block content %}
<div class="ui raised very padded text container segment">
  <p>Les services proposés:</p>
  <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/staff.html
{% extends "pages/base.html" %}
{% block content %}
<div class="ui raised very padded text container segment">
  <p>qui fournit le service?</p>
  <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
    </form>
  </div>
{% endblock %}

reservation/bookili/templates/pages/structure.html
{% extends "pages/base.html" %}

{% block content %}
  <div class="ui raised very padded text container segment">
    <form class="ui fluid form" method="post" action=".">
      {% csrf_token %}
      <div class="ui field">
        {{form}}
      </div>
      <input class="ui submit button blue" type="submit" name="valider" value="valider">
    </form>
  </div>
{% endblock %}